# Pindahkan variabel ke sini (Hapus spasi di sekitar tanda =)
DATABASE_URL=jdbc:mysql://localhost:3307/spring?createDatabaseIfNotExist=true
DATABASE_USERNAME=root
DATABASE_PASSWORD=Cokiber_2893

spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update

# Gunakan variabel yang sudah didefinisikan di atas
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver